use_wandb: False
use_sky: False
use_dynamic: False
use_pose_refine: False
use_metric: False

mode: 'vio'

device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /root/autodl-tmp/VINGS-Mono/dataset/KITTI_Sync/2011_09_30/2011_09_30_drive_0028_sync/
  module: datasets.kitti_sync
  rgb_strip: 1
  imu_delay: 0.05006

middleware:
  cov_times: 200
  max_cov: 3e3
  max_depth: 25

output:
  save_dir: /root/autodl-tmp/VINGS-Mono/output/

intrinsic:
  H: 370
  W: 1226
  fu: 707.0912
  fv: 707.0912
  cu: 183.1104
  cv: 601.8873
  bg: 0

frontend:
  weight: /root/autodl-tmp/VINGS-Mono/ckpts/droid.pth
  image_size: [240, 800]
  buffer: 80
  filter_thresh: 2.4
  c2i: None
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 4.0
  frontend_window: 5
  frontend_thresh: 16.0
  frontend_radius: 2
  active_window: 12
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4, -5, -6]
  translation_threshold: 0.5
  show_plot: False

adc_args:
  accum_thresh: 0.98

training_args:
  num_keyframe: 4
  iters: 24
  max_new_gaussians_per_frame: 15000
  lr:
    _xyz_lr: 0.00001
    _rgb_lr: 0.0001
    _opacity_lr: 0.05
    _scaling_lr: 0.001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 1.0
    alpha_loss: 1.0
    normal_loss: 0.1
    dist_loss: 0.0

use_vis: False

use_storage_manager: True
storage_manager:
  distance_threshold: 30.0
  run_interval: 4
  max_gpu_gaussians: 1500000
